version: "3.8"

services:
  backend:
    build: .
    container_name: backendskillmatch-backend
    ports:
      - "3000:3000"
    env_file:
      - .env  # This line loads your .env file
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: skillmatchDatabase
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
